/* eslint-disable react/no-unknown-property */
import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useLerpedMouse } from 'hooks'
import { useFrame } from '@react-three/fiber'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

export default function Model(props) {
  const ref = useRef<any>()
  const { dark, ...rest } = props
  const { nodes, materials } = useGLTF('/static/3d/rig.glb')
  const mouse = useLerpedMouse()
  const [shirtColor, setShirtColor] = useState(dark ? '#202020' : '#dadada')
  useEffect(() => {
    if (dark) {
      setShirtColor('#202020')
    } else {
      setShirtColor('#dadada')
    }
  }, [dark])
  useFrame((state) => {
    ref.current.rotation.y = mouse.current.x * Math.PI * 0.03
  })
  return (
    <group {...rest} dispose={null} ref={ref}>
      <group position={[0, 1.2, -0.05]} rotation={[0.25, 0, 0]}>
        <group position={[0, 0.2, 0]} rotation={[-0.25, 0, -0.01]}>
          <group position={[0, 0.28, 0]} rotation={[-0.03, 0, 0.01]}>
            <group position={[0, 0.22, 0]}>
              <group position={[0, 0.25, 0]} rotation={[0.23, 0, 0]}>
                <group position={[0, 0.08, 0]} rotation={[-0.1, 0, 0.03]} />
              </group>
              <group position={[0.02, 0.18, 0.1]} rotation={[-1.54, 0, -1.04]}>
                <group position={[0.01, 0.26, -0.03]} rotation={[1.79, 0.98, -1.68]}>
                  <group position={[0, 0.45, 0]} rotation={[-0.07, -0.2, -0.11]}>
                    <group position={[0, 0.41, 0]} rotation={[0.09, 0.02, -0.04]}>
                      <group position={[0, 0.09, 0.02]} rotation={[-0.55, 1.47, 0.59]}>
                        <group position={[0, 0.06, 0]} rotation={[-0.01, 0.21, 0.16]}>
                          <group position={[0, 0.06, 0]} rotation={[0, 0.02, -0.03]} />
                        </group>
                        <group position={[-0.06, -0.02, 0.01]} rotation={[-1.29, 0.9, 1.44]}>
                          <group position={[0, 0.04, 0]} rotation={[0.17, 0.26, -0.05]} />
                        </group>
                      </group>
                      <group position={[0, 0.08, 0]} rotation={[-1.08, 1.48, 0.89]}>
                        <group position={[0, 0.08, 0]} rotation={[0, 0.1, 0.03]}>
                          <group position={[0, 0.06, 0]} rotation={[0, -0.03, -0.03]} />
                        </group>
                      </group>
                      <group position={[0, 0.07, -0.02]} rotation={[-1.72, 1.48, 1.17]}>
                        <group position={[0, 0.07, 0]} rotation={[0.01, -0.03, 0.14]}>
                          <group position={[0, 0.05, 0]} rotation={[0, 0, -0.03]} />
                        </group>
                      </group>
                      <group position={[0, 0.07, -0.05]} rotation={[-2.92, 1.47, 2.09]}>
                        <group position={[0, 0.07, 0]} rotation={[0.03, -0.22, 0.19]}>
                          <group position={[0, 0.03, 0]} rotation={[0, 0, -0.02]} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group position={[-0.02, 0.18, 0.1]} rotation={[-1.54, 0, 1.04]}>
                <group position={[-0.01, 0.26, -0.03]} rotation={[1.79, -0.98, 1.68]}>
                  <group position={[0, 0.45, 0]} rotation={[-0.07, 0.2, 0.11]}>
                    <group position={[0, 0.41, 0]} rotation={[0.09, -0.02, 0.04]}>
                      <group position={[0, 0.09, 0.02]} rotation={[-0.55, -1.47, -0.59]}>
                        <group position={[0, 0.06, 0]} rotation={[-0.01, -0.21, -0.16]}>
                          <group position={[0, 0.06, 0]} rotation={[0, -0.02, 0.03]} />
                        </group>
                        <group position={[0.06, -0.02, 0.01]} rotation={[-1.29, -0.9, -1.44]}>
                          <group position={[0, 0.04, 0]} rotation={[0.17, -0.26, 0.05]} />
                        </group>
                      </group>
                      <group position={[0, 0.08, 0]} rotation={[-1.08, -1.48, -0.89]}>
                        <group position={[0, 0.08, 0]} rotation={[0, -0.1, -0.03]}>
                          <group position={[0, 0.06, 0]} rotation={[0, 0.03, 0.03]} />
                        </group>
                      </group>
                      <group position={[0, 0.07, -0.02]} rotation={[-1.72, -1.48, -1.17]}>
                        <group position={[0, 0.07, 0]} rotation={[0.01, 0.03, -0.14]}>
                          <group position={[0, 0.05, 0]} rotation={[0, 0, 0.03]} />
                        </group>
                      </group>
                      <group position={[0, 0.07, -0.05]} rotation={[-2.92, -1.47, -2.09]}>
                        <group position={[0, 0.07, 0]} rotation={[0.03, 0.22, -0.19]}>
                          <group position={[0, 0.03, 0]} rotation={[0, 0, 0.02]} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
        <group position={[0.16, 0.08, 0.04]} rotation={[2.89, 0, -0.03]}>
          <group position={[0, 0.56, 0]} rotation={[-0.01, 0, 0.04]}>
            <group position={[0, 0.6, 0]} rotation={[-1.3, 0.01, 0]} />
          </group>
        </group>
        <group position={[-0.15, 0.08, 0.04]} rotation={[2.89, 0, 0.03]}>
          <group position={[0, 0.56, 0]} rotation={[-0.01, 0, -0.04]}>
            <group position={[0, 0.6, 0]} rotation={[-1.3, -0.01, 0]} />
          </group>
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0.05, 1.2]} rotation={[1.82, 0, 0]}>
          <group position={[0, 0.2, 0]} rotation={[-0.25, 0, -0.01]}>
            <group position={[0, 0.28, 0]} rotation={[-0.03, 0, 0.01]}>
              <group position={[0, 0.22, 0]}>
                <group position={[0, 0.25, 0]} rotation={[0.23, 0, 0]}>
                  <group position={[0, 0.08, 0]} rotation={[-0.1, 0, 0.03]} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      <group position={[0, 1.29, -0.03]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, -0.02, 0.38]}>
          <group rotation={[1.57, 0, -0.01]}>
            <group position={[0, -0.28, 0]} rotation={[-1.57, -0.01, 0]}>
              <group rotation={[1.82, 0, 0]}>
                <group position={[0, -0.2, 0]}>
                  <group rotation={[-2.03, -0.82, -2.24]} />
                  <group position={[0.01, 0, 0]} rotation={[-2.03, 0.82, 2.24]} />
                  <group position={[0.16, 0.08, 0.04]} rotation={[-0.13, -1.33, -3.02]}>
                    <group position={[0, 0.56, 0]} rotation={[0.04, 0, 0]}>
                      <group position={[0, 0.6, 0]} rotation={[-1.65, 0.26, 1.82]} />
                      <group position={[0, 0.3, 0]} rotation={[0, 0.8, 0]} />
                    </group>
                    <group position={[0, 0.28, 0]} />
                  </group>
                  <group position={[-0.15, 0.08, 0.04]} rotation={[-0.13, 1.33, 3.02]}>
                    <group position={[0, 0.56, 0]} rotation={[0.04, 0, 0]}>
                      <group position={[0, 0.6, 0]} rotation={[-1.65, -0.26, -1.82]} />
                      <group position={[0, 0.3, 0]} rotation={[0, -0.8, 0]} />
                    </group>
                    <group position={[0, 0.28, 0]} />
                  </group>
                  <group position={[0.16, 0.08, 0.04]} rotation={[-1.82, 0, 0]}>
                    <group rotation={[1.69, -1.33, -3.02]}>
                      <group position={[0, 0.56, 0]} rotation={[0.04, 0, 0]}>
                        <group position={[0, 0.6, 0]} rotation={[-1.65, 0.26, 1.82]}>
                          <group position={[0, 0.21, 0]} rotation={[2.88, 0, -Math.PI]} />
                        </group>
                      </group>
                    </group>
                    <group rotation={[1.6, -1.31, -3.11]}>
                      <group rotation={[-0.02, 0.02, 0]} />
                    </group>
                  </group>
                  <group position={[0.16, 0.08, 0.04]} rotation={[-0.13, -1.33, -3.02]} />
                  <group position={[0.16, 0.08, 0.04]} rotation={[-0.13, -1.33, -3.02]}>
                    <group position={[0, 0.28, 0]}>
                      <group position={[0, 0.28, 0]} rotation={[0.04, 0, 0]}>
                        <group position={[0, 0.3, 0]}>
                          <group position={[0, 0.3, 0]} rotation={[-1.65, 0.26, 1.82]} />
                        </group>
                      </group>
                    </group>
                  </group>
                  <group position={[-0.15, 0.08, 0.04]} rotation={[-1.82, 0, 0]}>
                    <group rotation={[1.69, 1.33, 3.02]}>
                      <group position={[0, 0.56, 0]} rotation={[0.04, 0, 0]}>
                        <group position={[0, 0.6, 0]} rotation={[-1.65, -0.26, -1.82]}>
                          <group position={[0, 0.21, 0]} rotation={[2.88, 0, Math.PI]} />
                        </group>
                      </group>
                    </group>
                    <group rotation={[1.6, 1.31, 3.11]}>
                      <group rotation={[-0.02, -0.02, 0]} />
                    </group>
                  </group>
                  <group position={[-0.15, 0.08, 0.04]} rotation={[-0.13, 1.33, 3.02]} />
                  <group position={[-0.15, 0.08, 0.04]} rotation={[-0.13, 1.33, 3.02]}>
                    <group position={[0, 0.28, 0]}>
                      <group position={[0, 0.28, 0]} rotation={[0.04, 0, 0]}>
                        <group position={[0, 0.3, 0]}>
                          <group position={[0, 0.3, 0]} rotation={[-1.65, -0.26, -1.82]} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group rotation={[-0.25, 0, -0.01]} />
              </group>
            </group>
          </group>
        </group>
        <group position={[0, -0.02, 0.38]}>
          <group rotation={[1.54, 0, 0]}>
            <group rotation={[0.03, 0, -0.01]}>
              <group rotation={[-0.03, 0, 0.01]} />
            </group>
            <group position={[0, 0.22, 0]} rotation={[-1.54, 0, 0]}>
              <group rotation={[1.54, 0, 0]}>
                <group position={[0, 0.25, 0]} rotation={[0.23, 0, 0]}>
                  <group position={[0, 0.08, 0]} rotation={[-0.1, 0, 0.03]} />
                </group>
                <group position={[0, 0.25, 0]} rotation={[-1.54, 0, 0]}>
                  <group rotation={[1.71, 0.02, 0.02]}>
                    <group position={[0, 0.2, 0]} rotation={[-1.71, 0.02, -0.02]} />
                    <group position={[0, 0.08, 0]} />
                  </group>
                </group>
                <group position={[0.02, 0.18, 0.1]} rotation={[-1.54, 0, -1.04]}>
                  <group position={[0.01, 0.26, -0.03]} rotation={[-2.74, -0.43, -2.49]}>
                    <group position={[0, 0.45, 0]} rotation={[0.12, 0, 0]}>
                      <group position={[0, 0.41, 0]} rotation={[-0.02, 0, 0.1]} />
                      <group position={[0, 0.2, 0]} />
                    </group>
                    <group position={[0, 0.23, 0]} />
                  </group>
                  <group position={[0.01, 0.26, -0.03]} rotation={[0, 0, 1.04]}>
                    <group rotation={[-2.57, 0.09, -1.57]}>
                      <group position={[0, 0.45, 0]} rotation={[0.12, 0, 0]}>
                        <group position={[0, 0.41, 0]} rotation={[-0.02, 0, 0.1]} />
                      </group>
                    </group>
                    <group rotation={[-2.62, 0.04, -1.56]}>
                      <group rotation={[-0.06, 0.05, 0]} />
                    </group>
                  </group>
                  <group position={[0.01, 0.26, -0.03]} rotation={[-2.74, -0.43, -2.49]} />
                  <group position={[0.01, 0.26, -0.03]} rotation={[-2.74, -0.43, -2.49]}>
                    <group position={[0, 0.23, 0]}>
                      <group position={[0, 0.23, 0]} rotation={[0.12, 0, 0]}>
                        <group position={[0, 0.2, 0]}>
                          <group position={[0, 0.2, 0]} rotation={[-0.02, 0, 0.1]}>
                            <group position={[-0.02, 0.09, -0.01]} rotation={[-0.07, -0.72, 0]}>
                              <group position={[0, 0.06, 0]} rotation={[-2.32, 1.35, 2.33]}>
                                <group position={[0, 0.06, 0]} rotation={[0.03, 0, 0]} />
                              </group>
                              <group position={[-0.06, -0.02, 0.01]} rotation={[-1.75, 0.88, 1.81]}>
                                <group position={[0, 0.04, 0]} rotation={[0.17, 0, 0]} />
                              </group>
                              <group position={[0, 0.06, 0]} rotation={[-2.32, 1.35, 2.33]}>
                                <group position={[0, 0.06, 0]} rotation={[0.03, 0, 0]} />
                              </group>
                              <group position={[-0.06, -0.02, 0.01]} rotation={[-1.75, 0.88, 1.81]}>
                                <group position={[0, 0.04, 0]} rotation={[0.17, 0, 0]} />
                              </group>
                              <group position={[0, 0.06, 0]} rotation={[-2.32, 1.35, 2.33]}>
                                <group position={[0, 0.06, 0]} rotation={[0.03, 0, 0]}>
                                  <group position={[0, 0.03, 0]} rotation={[0.11, 0, 0]} />
                                </group>
                              </group>
                              <group position={[-0.06, -0.02, 0.01]} rotation={[-1.75, 0.88, 1.81]}>
                                <group position={[0, 0.04, 0]} rotation={[0.17, 0, 0]}>
                                  <group position={[0, 0.04, 0]} rotation={[0.02, 0, 0]} />
                                </group>
                              </group>
                            </group>
                            <group position={[0, 0.08, 0]} rotation={[-0.1, -0.67, -0.25]}>
                              <group position={[0, 0.08, 0]} rotation={[-2.85, 1.46, 2.86]}>
                                <group position={[0, 0.06, 0]} rotation={[0.03, 0, 0]} />
                              </group>
                              <group position={[0, 0.08, 0]} rotation={[-2.85, 1.46, 2.86]}>
                                <group position={[0, 0.06, 0]} rotation={[0.03, 0, 0]} />
                              </group>
                              <group position={[0, 0.08, 0]} rotation={[-2.85, 1.46, 2.86]}>
                                <group position={[0, 0.06, 0]} rotation={[0.03, 0, 0]}>
                                  <group position={[0, 0.04, 0]} rotation={[0.05, 0, 0]} />
                                </group>
                              </group>
                            </group>
                            <group position={[0.02, 0.07, 0.01]} rotation={[-0.11, -0.62, -0.62]}>
                              <group position={[0, 0.07, 0]} rotation={[-1.97, 1.41, 1.97]}>
                                <group position={[0, 0.05, 0]} rotation={[0.03, 0, 0]} />
                              </group>
                              <group position={[0, 0.07, 0]} rotation={[-1.97, 1.41, 1.97]}>
                                <group position={[0, 0.05, 0]} rotation={[0.03, 0, 0]} />
                              </group>
                              <group position={[0, 0.07, 0]} rotation={[-1.97, 1.41, 1.97]}>
                                <group position={[0, 0.05, 0]} rotation={[0.03, 0, 0]}>
                                  <group position={[0, 0.04, 0]} rotation={[0.05, 0, 0]} />
                                </group>
                              </group>
                            </group>
                            <group position={[0.04, 0.07, 0.03]} rotation={[-0.03, -0.54, -0.84]}>
                              <group position={[0, 0.07, 0]} rotation={[-1.32, 1.38, 1.32]}>
                                <group position={[0, 0.03, 0]} rotation={[0.02, 0, 0]} />
                              </group>
                              <group position={[0, 0.07, 0]} rotation={[-1.32, 1.38, 1.32]}>
                                <group position={[0, 0.03, 0]} rotation={[0.02, 0, 0]} />
                              </group>
                              <group position={[0, 0.07, 0]} rotation={[-1.32, 1.38, 1.32]}>
                                <group position={[0, 0.03, 0]} rotation={[0.02, 0, 0]}>
                                  <group position={[0, 0.02, 0]} rotation={[-0.01, 0, 0]} />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group position={[-0.02, 0.18, 0.1]} rotation={[-1.54, 0, 1.04]}>
                  <group position={[-0.01, 0.26, -0.03]} rotation={[-2.74, 0.43, 2.49]}>
                    <group position={[0, 0.45, 0]} rotation={[0.12, 0, 0]}>
                      <group position={[0, 0.41, 0]} rotation={[-0.02, 0, -0.1]} />
                      <group position={[0, 0.2, 0]} />
                    </group>
                    <group position={[0, 0.23, 0]} />
                  </group>
                  <group position={[-0.01, 0.26, -0.03]} rotation={[0, 0, -1.04]}>
                    <group rotation={[-2.57, -0.09, 1.57]}>
                      <group position={[0, 0.45, 0]} rotation={[0.12, 0, 0]}>
                        <group position={[0, 0.41, 0]} rotation={[-0.02, 0, -0.1]} />
                      </group>
                    </group>
                    <group rotation={[-2.62, -0.04, 1.56]}>
                      <group rotation={[-0.06, -0.05, 0]} />
                    </group>
                  </group>
                  <group position={[-0.01, 0.26, -0.03]} rotation={[-2.74, 0.43, 2.49]} />
                  <group position={[-0.01, 0.26, -0.03]} rotation={[-2.74, 0.43, 2.49]}>
                    <group position={[0, 0.23, 0]}>
                      <group position={[0, 0.23, 0]} rotation={[0.12, 0, 0]}>
                        <group position={[0, 0.2, 0]}>
                          <group position={[0, 0.2, 0]} rotation={[-0.02, 0, -0.1]}>
                            <group position={[0.02, 0.09, -0.01]} rotation={[-0.07, 0.72, 0]}>
                              <group position={[0, 0.06, 0]} rotation={[-2.32, -1.35, -2.33]}>
                                <group position={[0, 0.06, 0]} rotation={[0.03, 0, 0]} />
                              </group>
                              <group
                                position={[0.06, -0.02, 0.01]}
                                rotation={[-1.75, -0.88, -1.81]}
                              >
                                <group position={[0, 0.04, 0]} rotation={[0.17, 0, 0]} />
                              </group>
                              <group position={[0, 0.06, 0]} rotation={[-2.32, -1.35, -2.33]}>
                                <group position={[0, 0.06, 0]} rotation={[0.03, 0, 0]} />
                              </group>
                              <group
                                position={[0.06, -0.02, 0.01]}
                                rotation={[-1.75, -0.88, -1.81]}
                              >
                                <group position={[0, 0.04, 0]} rotation={[0.17, 0, 0]} />
                              </group>
                              <group position={[0, 0.06, 0]} rotation={[-2.32, -1.35, -2.33]}>
                                <group position={[0, 0.06, 0]} rotation={[0.03, 0, 0]}>
                                  <group position={[0, 0.03, 0]} rotation={[0.11, 0, 0]} />
                                </group>
                              </group>
                              <group
                                position={[0.06, -0.02, 0.01]}
                                rotation={[-1.75, -0.88, -1.81]}
                              >
                                <group position={[0, 0.04, 0]} rotation={[0.17, 0, 0]}>
                                  <group position={[0, 0.04, 0]} rotation={[0.02, 0, 0]} />
                                </group>
                              </group>
                            </group>
                            <group position={[0, 0.08, 0]} rotation={[-0.1, 0.67, 0.25]}>
                              <group position={[0, 0.08, 0]} rotation={[-2.85, -1.46, -2.86]}>
                                <group position={[0, 0.06, 0]} rotation={[0.03, 0, 0]} />
                              </group>
                              <group position={[0, 0.08, 0]} rotation={[-2.85, -1.46, -2.86]}>
                                <group position={[0, 0.06, 0]} rotation={[0.03, 0, 0]} />
                              </group>
                              <group position={[0, 0.08, 0]} rotation={[-2.85, -1.46, -2.86]}>
                                <group position={[0, 0.06, 0]} rotation={[0.03, 0, 0]}>
                                  <group position={[0, 0.04, 0]} rotation={[0.05, 0, 0]} />
                                </group>
                              </group>
                            </group>
                            <group position={[-0.02, 0.07, 0.01]} rotation={[-0.11, 0.62, 0.62]}>
                              <group position={[0, 0.07, 0]} rotation={[-1.97, -1.41, -1.97]}>
                                <group position={[0, 0.05, 0]} rotation={[0.03, 0, 0]} />
                              </group>
                              <group position={[0, 0.07, 0]} rotation={[-1.97, -1.41, -1.97]}>
                                <group position={[0, 0.05, 0]} rotation={[0.03, 0, 0]} />
                              </group>
                              <group position={[0, 0.07, 0]} rotation={[-1.97, -1.41, -1.97]}>
                                <group position={[0, 0.05, 0]} rotation={[0.03, 0, 0]}>
                                  <group position={[0, 0.04, 0]} rotation={[0.05, 0, 0]} />
                                </group>
                              </group>
                            </group>
                            <group position={[-0.04, 0.07, 0.03]} rotation={[-0.03, 0.54, 0.84]}>
                              <group position={[0, 0.07, 0]} rotation={[-1.32, -1.38, -1.32]}>
                                <group position={[0, 0.03, 0]} rotation={[0.02, 0, 0]} />
                              </group>
                              <group position={[0, 0.07, 0]} rotation={[-1.32, -1.38, -1.32]}>
                                <group position={[0, 0.03, 0]} rotation={[0.02, 0, 0]} />
                              </group>
                              <group position={[0, 0.07, 0]} rotation={[-1.32, -1.38, -1.32]}>
                                <group position={[0, 0.03, 0]} rotation={[0.02, 0, 0]}>
                                  <group position={[0, 0.02, 0]} rotation={[-0.01, 0, 0]} />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      <group position={[1.11, 2.07, -0.01]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[-2.57, 0, -1.47]} />
      </group>
      <group position={[0.67, 2.8, 0.45]} rotation={[-Math.PI / 2, 0, 0]} />
      <group position={[-1.11, 2.07, -0.01]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[-2.57, 0, 1.47]} />
      </group>
      <group position={[-0.67, 2.8, 0.45]} rotation={[-Math.PI / 2, 0, 0]} />
      <group position={[0.16, 0.11, 0.01]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, -0.21, -0.06]}>
          <group position={[-0.05, 0.34, -0.05]}>
            <group position={[0.1, 0, 0]}>
              <group position={[-0.05, 0, 0]}>
                <group position={[0, -0.34, 0.05]}>
                  <group position={[0, 0.21, 0.06]} rotation={[-2.88, 0, 0]}>
                    <group position={[0, 0.21, 0]} rotation={[2.88, 0, 0]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      <group position={[1.29, 0.72, -0.27]} rotation={[-Math.PI / 2, 0, 0]} />
      <group position={[-0.16, 0.11, 0.01]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, -0.21, -0.06]}>
          <group position={[0.05, 0.34, -0.05]}>
            <group position={[-0.1, 0, 0]}>
              <group position={[0.05, 0, 0]}>
                <group position={[0, -0.34, 0.05]}>
                  <group position={[0, 0.21, 0.06]} rotation={[-2.88, 0, 0]}>
                    <group position={[0, 0.21, 0]} rotation={[2.88, 0, 0]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
      <group position={[-1.29, 0.72, -0.27]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body002.geometry}
        material={materials.Skin}
        position={[0, 0.99, -0.01]}
        scale={1.07}
      />
      <group position={[0.16, 0.85, 0]} scale={[0.12, 0.48, 0.1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Base}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_2.geometry}
          material={materials.Skin}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath.geometry}
        material={materials.Lace}
        position={[0.16, 0.12, 0.25]}
        rotation={[1.51, 0, 0]}
        scale={0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath001.geometry}
        material={materials.Lace}
        position={[0.16, 0.13, 0.21]}
        rotation={[1.64, 0, 0]}
        scale={0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath003.geometry}
        material={materials.Lace}
        position={[0.16, 0.2, 0.12]}
        rotation={[2.42, 0, 0]}
        scale={[0.04, 0.04, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.NurbsPath002.geometry}
        material={materials.Lace}
        position={[0.16, 0.15, 0.16]}
        rotation={[1.97, 0, 0]}
        scale={[0.04, 0.04, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pant.geometry}
        material={materials.Base}
        position={[0, 1.24, 0]}
        scale={[1.29, 1.81, 1.21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shirt.geometry}
        material={materials.shirt}
        material-color={shirtColor}
        position={[0, 0.99, -0.01]}
        scale={1.07}
      />
      <group position={[0.16, 0.15, 0.02]} scale={0.49}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials['Base.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_2.geometry}
          material={materials['Rubber.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_3.geometry}
          material={materials['Inner Shoe']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Skin}
        position={[0, 2.56, 0.28]}
        scale={[0.03, 0.04, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bred.geometry}
        material={materials.hair}
        position={[0, 2.61, -0.01]}
        scale={[-0.32, -0.29, -0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.Rubber}
        position={[0, 2.44, 0.19]}
        scale={[0.09, 0.01, 0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.Rubber}
        position={[0, 2.49, 0.18]}
        rotation={[0, 0, -Math.PI]}
        scale={[0.13, 0.02, 0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.hair}
        position={[0, 3.01, 0.01]}
        scale={[0.43, 0.31, 0.36]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials.Eye}
        position={[0.1, 2.63, 0.25]}
        scale={[-0.02, -0.03, -0.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere001.geometry}
        material={materials.lidah}
        position={[0, 2.46, 0.15]}
        scale={[0.05, 0.02, 0.05]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.Skin}
        position={[0.3, 2.61, -0.03]}
        rotation={[1.57, -0.26, 0]}
        scale={[0.08, 0.03, 0.1]}
      />
      <group position={[0, 2.61, -0.01]} scale={[-0.32, -0.29, -0.31]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials.Skin}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_2.geometry}
          material={materials['inner mounth']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair.geometry}
        material={materials.hair}
        position={[0, 2.61, -0.01]}
        scale={[-0.32, -0.29, -0.31]}
      />
    </group>
  )
}

useGLTF.preload('/static/3d/rig.glb')
