/* eslint-disable react/no-unknown-property */
/*
  Auto-generated by Spline
*/
import * as THREE from 'three'
import { useRef } from 'react'
import { Clone, Float, PerspectiveCamera, useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { useLerpedMouse } from 'hooks'

const cameraTargetPosition = new THREE.Vector3(0, -10, 211)
export default function ThreeModel({ ...props }) {
  const { nodes, materials } = useGLTF('/static/3d/minimul.gltf')
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const camera = useRef<any>()
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const sceneContent = useRef<any>()
  const mouse = useLerpedMouse()
  const size = useThree((state) => state.size)
  const isMobile = size.width < 768

  const lerpedScroll = useRef(0)

  useFrame(() => {
    // lerp the scroll
    lerpedScroll.current += (0 - lerpedScroll.current) * 0.08

    // animate the camera
    const zStart = isMobile ? 2000 : 1100
    const zEnd = isMobile ? -300 : -40
    const xMin = isMobile ? -600 : -800
    const xMax = isMobile ? -200 : 0
    const targetX = isMobile ? -50 : -300
    const yBase = isMobile ? 50 : 200
    const yRange = isMobile ? 100 : 200
    const t = lerpedScroll.current
    const arc = Math.sin(t * Math.PI)
    camera.current.position.set(
      THREE.MathUtils.lerp(xMax, xMin, arc),
      arc * yRange + yBase,
      THREE.MathUtils.lerp(zStart, zEnd, t)
    )
    cameraTargetPosition.x = THREE.MathUtils.lerp(0, targetX, arc)
    camera.current.lookAt(cameraTargetPosition)
    sceneContent.current.position.x = (1 - t) * 150
    sceneContent.current.rotation.y = mouse.current.x * Math.PI * 0.03
  })

  return (
    <>
      <group {...props} dispose={null}>
        <PerspectiveCamera
          name="Camera"
          ref={camera}
          makeDefault={true}
          far={8000}
          near={5}
          fov={45}
        />
        <group ref={sceneContent}>
          <group {...props} dispose={null}>
            <group position={[51, 153.92, 37.16]}>
              <group
                position={[143.33, -48.47, 215.43]}
                rotation={[0.01, -0.29, -0.42]}
                scale={0.81}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle.geometry}
                  material={materials.Shirt}
                  position={[-0.01, 1.49, -7.99]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Sphere_2.geometry}
                  material={materials.Material}
                  position={[-11.35, 3.23, -2.16]}
                  scale={[0.9, 0.9, 0.91]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Sphere_3.geometry}
                  material={materials.Material}
                  position={[0.46, 3.25, -2.07]}
                  scale={[0.9, 0.9, 0.91]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Sphere_4.geometry}
                  material={materials.Material}
                  position={[11.82, 3.26, -1.97]}
                  scale={[0.9, 0.9, 0.91]}
                />
              </group>
              <group position={[-145.78, 29.15, -61.38]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Ellipse.geometry}
                  material={materials['Material.002']}
                  position={[-14.18, 4.69, 3.52]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_2.geometry}
                  material={materials['Material.002']}
                  position={[23.28, 10.09, 3.52]}
                  scale={[1, 0.85, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_3.geometry}
                  material={materials['Material.002']}
                  position={[14.28, -0.17, 3.52]}
                  scale={[1, 0.85, 1]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_3001.geometry}
                  material={materials['Material.001']}
                  position={[23.29, 4.97, -5.52]}
                />
              </group>
            </group>
            <group name="icon" position={[51, 153.92, 37.16]}>
              <Float floatIntensity={3} speed={2}>
                <Clone object={nodes['Triangle']} />
              </Float>
              <Float floatIntensity={3} speed={2}>
                <Clone object={nodes['Cube_2']} />
              </Float>
              <Float floatIntensity={3} speed={2}>
                <Clone object={nodes['Shape']} />
              </Float>
            </group>
            <group position={[54.84, 0.52, 141.56]}>
              <group position={[5.06, 49.66, -37.85]} rotation={[0, -Math.PI / 6, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_2003.geometry}
                  material={materials.Shirt}
                  position={[0.97, 83.68, -58.41]}
                  rotation={[0.22, -0.17, 0]}
                  scale={1.33}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.body001.geometry}
                  material={materials.jacket}
                  position={[0.15, 16.28, -51.27]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.line.geometry}
                  material={materials.Hair}
                  position={[-8.34, -29.82, -1.07]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes['hand-15'].geometry}
                  material={materials.Skin}
                  position={[-69.05, -69.33, 71.27]}
                  rotation={[1.81, 0.31, -0.24]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes['hand-15_2'].geometry}
                  material={materials.Skin}
                  position={[57.19, -72.48, 62.33]}
                  rotation={[-1.37, -0.04, -0.48]}
                  scale={-1}
                />
              </group>
              <group position={[17.29, -213.5, -71.28]} rotation={[0, -Math.PI / 6, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_8001.geometry}
                  material={materials.wood}
                  position={[-2.38, 97.16, 2.31]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 4]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_6001.geometry}
                  material={materials.wood}
                  position={[67.32, -2.73, 67.27]}
                  rotation={[1.4, -1.48, 1.48]}
                  scale={1.24}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_9001.geometry}
                  material={materials.wood}
                  position={[-2.31, 98.83, -2.38]}
                  rotation={[Math.PI / 2, 0, Math.PI / 4]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_2002.geometry}
                  material={materials.wood}
                  position={[3.25, 110.66, 3.32]}
                  scale={1.24}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_4001.geometry}
                  material={materials.wood}
                  position={[67.27, -2.73, -67.32]}
                  rotation={[0.09, 0.02, 0.09]}
                  scale={1.24}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_5001.geometry}
                  material={materials.wood}
                  position={[-67.33, -2.73, 67.32]}
                  rotation={[-0.09, 0, -0.09]}
                  scale={1.24}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_6002.geometry}
                  material={materials.wood}
                  position={[-67.32, -2.73, -67.33]}
                  rotation={[-Math.PI / 2, -1.48, -1.66]}
                  scale={1.24}
                />
              </group>
              <group
                position={[-47.41, 10.18, 45.32]}
                rotation={[-2.97, 0.52, 3.06]}
                scale={[0.64, 0.7, 0.7]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_2008.geometry}
                  material={materials.Hair}
                  position={[0, -0.21, -81.43]}
                  rotation={[-Math.PI / 9, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_4003.geometry}
                  material={materials.Hair}
                  position={[0, -62.82, -3.88]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.83}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_5003.geometry}
                  material={materials.tpad}
                  position={[0, -66.01, 62.64]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.83}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle002.geometry}
                  material={materials.mac}
                  position={[0, -5.45, -85.58]}
                  rotation={[-Math.PI / 9, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_3007.geometry}
                  material={materials.mac}
                  position={[0, -66.85, 15.84]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
              </group>
              <group position={[18.51, 200.48, -52.92]} rotation={[0.4, -0.49, 0.19]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_16.geometry}
                  material={materials.Skin}
                  position={[38.42, -12.67, -6.07]}
                  rotation={[Math.PI, 0, 0]}
                  scale={-1}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_13.geometry}
                  material={materials.Hair}
                  position={[-21.98, 10.29, 29.17]}
                  rotation={[-0.04, -0.41, 3.03]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_15.geometry}
                  material={materials.Hair}
                  position={[11.67, 1.12, 30.38]}
                  rotation={[0, Math.PI / 9, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube008.geometry}
                  material={materials.Skin}
                  position={[-44.39, -12.67, -6.07]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_4005.geometry}
                  material={materials.Hair}
                  position={[49.14, -11.33, 15.7]}
                  rotation={[3.09, 0.34, 0.02]}
                  scale={[-1, -1, -1.14]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube006.geometry}
                  material={materials.Hair}
                  position={[-4.85, -41.62, 22.49]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_3005.geometry}
                  material={materials.Hair}
                  position={[-3.71, -39.93, -45.36]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_12.geometry}
                  material={materials.Hair}
                  position={[12.6, 6.38, 31.35]}
                  rotation={[-0.1, 0.28, 0.2]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_14.geometry}
                  material={materials.Hair}
                  position={[-21.34, 1.12, 28.72]}
                  rotation={[0, -Math.PI / 9, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_2008.geometry}
                  material={materials.Hair}
                  position={[34.85, 14.43, 27.35]}
                  rotation={[-3.12, 0.61, -0.14]}
                  scale={[-1, -1, -1.36]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_5001.geometry}
                  material={materials.Hair}
                  position={[-45.39, 23.81, 20.24]}
                  rotation={[-0.09, 0.35, -0.48]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube007.geometry}
                  material={materials.Hair}
                  position={[-51.46, 1.7, 11.03]}
                  rotation={[-0.09, 0.35, 0.24]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Sphere_2001.geometry}
                  material={materials.Skin}
                  position={[-2.88, -8.51, -8.67]}
                />
              </group>
              <group
                position={[31.88, 137.51, -80.19]}
                rotation={[-1.13, -0.24, -0.47]}
                scale={0.59}
              >
                <group
                  position={[55.95, -61.83, 1.78]}
                  rotation={[Math.PI / 2, 1.48, -Math.PI / 2]}
                  scale={0.7}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Rectangle_3006.geometry}
                    material={materials.mac}
                    position={[-1.2, -0.12, 15.36]}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Rectangle_2007.geometry}
                    material={materials.tpad}
                    position={[-1.2, -0.12, 8.51]}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube005.geometry}
                    material={materials.Hair}
                    position={[0, 0, -7.36]}
                  />
                </group>
                <group
                  position={[-58.3, -62.56, 1.56]}
                  rotation={[Math.PI / 2, -1.4, -Math.PI / 2]}
                  scale={0.7}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Rectangle_2006.geometry}
                    material={materials.tpad}
                    position={[-1.2, -0.12, 8.51]}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube004.geometry}
                    material={materials.Hair}
                    position={[0, 0, -7.36]}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Rectangle_3005.geometry}
                    material={materials.mac}
                    position={[-1.2, -0.12, 15.36]}
                  />
                </group>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder.geometry}
                  material={materials.mac}
                  position={[72.07, -48.41, 2.68]}
                  rotation={[0, 0, -0.17]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_2001.geometry}
                  material={materials.mac}
                  position={[-76.47, -48.31, 2.68]}
                  rotation={[0, 0, 0.26]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus002.geometry}
                  material={materials.mac}
                  position={[-2.41, -33.31, 1.83]}
                  rotation={[0, 0, -Math.PI / 2]}
                  scale={[1.05, 1, 1]}
                />
              </group>
              <group
                position={[-99.24, -294.46, 140.87]}
                rotation={[-0.09, -Math.PI / 6, -0.17]}
                scale={1.2}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_2007.geometry}
                  material={nodes.Cube_2007.material}
                  position={[-0.12, -11.5, 2.05]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus001.geometry}
                  material={materials.rope}
                  position={[0, -6.17, -0.33]}
                  rotation={[-2.34, 0, 2.36]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_3004.geometry}
                  material={materials.Hair}
                  position={[11.29, -9.72, -3.39]}
                  rotation={[-1.57, 1.48, 0.35]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_4002.geometry}
                  material={materials.Hair}
                  position={[11.45, -11.57, 5.14]}
                  rotation={[-1.57, 1.48, 0.35]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus_2001.geometry}
                  material={materials.rope}
                  position={[0, -4.82, -6.39]}
                  rotation={[-2.34, 0, 2.36]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus_4001.geometry}
                  material={materials.rope}
                  position={[0, 0.78, -15.38]}
                  rotation={[-2.34, 0, 2.36]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_3002.geometry}
                  material={materials.Skin}
                  position={[-0.07, 25.37, -26.1]}
                  rotation={[-0.17, 0, 0]}
                  scale={0.65}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_2005.geometry}
                  material={materials.inshole}
                  position={[-0.01, -27.5, 0.54]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_5002.geometry}
                  material={materials.Hair}
                  position={[11.67, -14.09, 13.97]}
                  rotation={[-1.57, 1.48, 0.35]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus_3001.geometry}
                  material={materials.rope}
                  position={[0, -2.43, -11.25]}
                  rotation={[-2.34, 0, 2.36]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus_5001.geometry}
                  material={materials.rope}
                  position={[0, 4.97, -18.7]}
                  rotation={[-2.34, 0, 2.36]}
                />
              </group>
              <group
                position={[-45.75, -283.03, 87.46]}
                rotation={[-2.83, 0.2, -0.49]}
                scale={-1.2}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_3003.geometry}
                  material={materials.Hair}
                  position={[11.29, -9.72, -3.39]}
                  rotation={[-Math.PI / 2, 1.48, Math.PI / 9]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_4001.geometry}
                  material={materials.Hair}
                  position={[11.45, -11.57, 5.14]}
                  rotation={[-Math.PI / 2, 1.48, Math.PI / 9]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_5001.geometry}
                  material={materials.Hair}
                  position={[11.67, -14.09, 13.97]}
                  rotation={[-Math.PI / 2, 1.48, Math.PI / 9]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus.geometry}
                  material={materials.rope}
                  position={[0, -6.17, -0.33]}
                  rotation={[-2.34, 0, 2.36]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus_3.geometry}
                  material={materials.rope}
                  position={[0, -2.43, -11.25]}
                  rotation={[-2.34, 0, 2.36]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus_5.geometry}
                  material={materials.rope}
                  position={[0, 4.97, -18.7]}
                  rotation={[-2.34, 0, 2.36]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube_2006.geometry}
                  material={nodes.Cube_2006.material}
                  position={[-0.12, -11.5, 2.05]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder_3001.geometry}
                  material={materials.Skin}
                  position={[-2.99, 24.83, -28.74]}
                  rotation={[-Math.PI / 9, 0, 0.09]}
                  scale={0.65}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Rectangle_2004.geometry}
                  material={materials.inshole}
                  position={[-0.01, -27.5, 0.54]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus_2.geometry}
                  material={materials.rope}
                  position={[0, -4.82, -6.39]}
                  rotation={[-2.34, 0, 2.36]}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Torus_4.geometry}
                  material={materials.rope}
                  position={[0, 0.78, -15.38]}
                  rotation={[-2.34, 0, 2.36]}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder001.geometry}
                material={materials.Skin}
                position={[33.52, 151.87, -85.2]}
                rotation={[0.4, -0.49, 0.19]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.leg.geometry}
                material={materials.jeans}
                position={[31.27, -40.93, -83.02]}
                rotation={[0, -Math.PI / 6, 0]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube.geometry}
              material={materials.Material}
            />
          </group>
          <pointLight
            name="Point Light"
            // castShadow
            intensity={0.6}
            distance={1011}
            color="#c2d3fe"
            position={[319.47, 509.35, -330.97]}
            rotation={[0, -Math.PI / 6, 0]}
          />
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.8}
            shadow-mapSize-width={2048}
            shadow-mapSize-height={2048}
            shadow-camera-near={1}
            shadow-camera-far={1500}
            shadow-camera-left={-1500}
            shadow-camera-right={1500}
            shadow-camera-top={1500}
            shadow-camera-bottom={-1500}
            color="#feefe8"
            position={[-189.41, 460.06, 327.57]}
          />
          <hemisphereLight
            name="Default Ambient Light"
            intensity={0.75}
            color="#eaeaea"
            position={[0, 1, 0]}
          />
        </group>
      </group>
    </>
  )
}

useGLTF.preload('/minimul.gltf')
